const data = [
    {
        "Module": "Common",
        "Sub module": "Master",
        "Form": "Masters Ribbon",
        "Task": "Edit",
        "Date": "",
        "Deadline": "",
        "Status": "Done",
        "Codeplayers Remarks": "",
        "Client Remarks": ""
    },
    {
        "Module": "Common",
        "Sub module": "Master",
        "Form": "Masters Ribbon",
        "Task": "View",
        "Date": "",
        "Deadline": "",
        "Status": "Done",
        "Codeplayers Remarks": "",
        "Client Remarks": ""
    },
    {
        "Module": "Common",
        "Sub module": "Master",
        "Form": "Masters Ribbon",
        "Task": "Display",
        "Date": "",
        "Deadline": "",
        "Status": "TRP",
        "Codeplayers Remarks": "",
        "Client Remarks": ""
    },
    {
        "Module": "Common",
        "Sub module": "Master",
        "Form": "Masters Ribbon",
        "Task": "Active/Inactive",
        "Date": "",
        "Deadline": "",
        "Status": "CRP",
        "Codeplayers Remarks": "",
        "Client Remarks": ""
    },
    {
        "Module": "Common",
        "Sub module": "Master",
        "Form": "Masters Ribbon",
        "Task": "Approve",
        "Date": "",
        "Deadline": "",
        "Status": "TRP",
        "Codeplayers Remarks": "",
        "Client Remarks": ""
    },
    {
        "Module": "Common",
        "Sub module": "Master",
        "Form": "Masters Ribbon",
        "Task": "Codification",
        "Date": "",
        "Deadline": "",
        "Status": "Pending",
        "Codeplayers Remarks": "",
        "Client Remarks": ""
    },
    {
        "Module": "Finance & Accounts",
        "Sub module": "Master",
        "Form": "Account Group",
        "Task": "Concept",
        "Date": "",
        "Deadline": "",
        "Status": "Done",
        "Codeplayers Remarks": "",
        "Client Remarks": ""
    },
    {
        "Module": "Finance & Accounts",
        "Sub module": "Master",
        "Form": "Account Group",
        "Task": "New ",
        "Date": "",
        "Deadline": "",
        "Status": "TRP",
        "Codeplayers Remarks": "",
        "Client Remarks": ""
    },
    {
        "Module": "Finance & Accounts",
        "Sub module": "Master",
        "Form": "Account Group",
        "Task": "Group Codification",
        "Date": "",
        "Deadline": "",
        "Status": "Done",
        "Codeplayers Remarks": "",
        "Client Remarks": ""
    },
    {
        "Module": "Finance & Accounts",
        "Sub module": "Master",
        "Form": "Area",
        "Task": "Concept",
        "Date": "",
        "Deadline": "",
        "Status": "CRP",
        "Codeplayers Remarks": "",
        "Client Remarks": ""
    },
    {
        "Module": "Finance & Accounts",
        "Sub module": "Master",
        "Form": "Area",
        "Task": "New ",
        "Date": "",
        "Deadline": "",
        "Status": "Pending",
        "Codeplayers Remarks": "",
        "Client Remarks": ""
    },
    {
        "Module": "Finance & Accounts",
        "Sub module": "Master",
        "Form": "Account Ledger",
        "Task": "Concept",
        "Date": "",
        "Deadline": "",
        "Status": "Done",
        "Codeplayers Remarks": "",
        "Client Remarks": ""
    },
    {
        "Module": "Finance & Accounts",
        "Sub module": "Master",
        "Form": "Account Ledger",
        "Task": "New ",
        "Date": "",
        "Deadline": "",
        "Status": "TRP",
        "Codeplayers Remarks": "",
        "Client Remarks": ""
    },
    {
        "Module": "Finance & Accounts",
        "Sub module": "Master",
        "Form": "Account Ledger",
        "Task": "Extra Feature",
        "Date": "",
        "Deadline": "",
        "Status": "Done",
        "Codeplayers Remarks": "",
        "Client Remarks": ""
    },
    {
        "Module": "Finance & Accounts",
        "Sub module": "Master",
        "Form": "Account Ledger",
        "Task": "Ledger Codification",
        "Date": "",
        "Deadline": "",
        "Status": "TRP",
        "Codeplayers Remarks": "",
        "Client Remarks": ""
    },
    {
        "Module": "Raw Materials",
        "Sub module": "Master",
        "Form": "Stock Group",
        "Task": "Concept",
        "Date": "",
        "Deadline": "",
        "Status": "Done",
        "Codeplayers Remarks": "",
        "Client Remarks": ""
    },
    {
        "Module": "Raw Materials",
        "Sub module": "Master",
        "Form": "Stock Group",
        "Task": "New ",
        "Date": "",
        "Deadline": "",
        "Status": "CRP",
        "Codeplayers Remarks": "",
        "Client Remarks": ""
    },
    {
        "Module": "Raw Materials",
        "Sub module": "Master",
        "Form": "Stock Group",
        "Task": "Group Codification",
        "Date": "",
        "Deadline": "",
        "Status": "Done",
        "Codeplayers Remarks": "",
        "Client Remarks": ""
    },
    {
        "Module": "Raw Materials",
        "Sub module": "Master",
        "Form": "Stock Item",
        "Task": "Concept",
        "Date": "",
        "Deadline": "",
        "Status": "CRP",
        "Codeplayers Remarks": "",
        "Client Remarks": ""
    },
    {
        "Module": "Raw Materials",
        "Sub module": "Master",
        "Form": "Stock Item",
        "Task": "New ",
        "Date": "",
        "Deadline": "",
        "Status": "TRP",
        "Codeplayers Remarks": "",
        "Client Remarks": ""
    },
    {
        "Module": "Raw Materials",
        "Sub module": "Master",
        "Form": "Stock Item",
        "Task": "Extra Feature",
        "Date": "",
        "Deadline": "",
        "Status": "Done",
        "Codeplayers Remarks": "",
        "Client Remarks": ""
    },
    {
        "Module": "Raw Materials",
        "Sub module": "Master",
        "Form": "Stock Item",
        "Task": "Item Codification",
        "Date": "",
        "Deadline": "",
        "Status": "CRP",
        "Codeplayers Remarks": "",
        "Client Remarks": ""
    },
    {
        "Module": "Common",
        "Sub module": "Transactions",
        "Form": "Masters Ribbon",
        "Task": "Edit",
        "Date": "",
        "Deadline": "",
        "Status": "TRP",
        "Codeplayers Remarks": "",
        "Client Remarks": ""
    },
    {
        "Module": "Common",
        "Sub module": "Transactions",
        "Form": "Masters Ribbon",
        "Task": "Void",
        "Date": "",
        "Deadline": "",
        "Status": "Done",
        "Codeplayers Remarks": "",
        "Client Remarks": ""
    },
    {
        "Module": "Common",
        "Sub module": "Transactions",
        "Form": "Masters Ribbon",
        "Task": "Delete",
        "Date": "",
        "Deadline": "",
        "Status": "Done",
        "Codeplayers Remarks": "",
        "Client Remarks": ""
    },
    {
        "Module": "Common",
        "Sub module": "Transactions",
        "Form": "Masters Ribbon",
        "Task": "Approve",
        "Date": "",
        "Deadline": "",
        "Status": "CRP",
        "Codeplayers Remarks": "",
        "Client Remarks": ""
    },
    {
        "Module": "Common",
        "Sub module": "Transactions",
        "Form": "Masters Ribbon",
        "Task": "Print",
        "Date": "",
        "Deadline": "",
        "Status": "TRP",
        "Codeplayers Remarks": "",
        "Client Remarks": ""
    },
    {
        "Module": "Common",
        "Sub module": "Transactions",
        "Form": "Masters Ribbon",
        "Task": "Whatsapp",
        "Date": "",
        "Deadline": "",
        "Status": "Done",
        "Codeplayers Remarks": "",
        "Client Remarks": ""
    },
    {
        "Module": "Common",
        "Sub module": "Transactions",
        "Form": "Masters Ribbon",
        "Task": "EMail",
        "Date": "",
        "Deadline": "",
        "Status": "CRP",
        "Codeplayers Remarks": "",
        "Client Remarks": ""
    },
    {
        "Module": "Common",
        "Sub module": "Transactions",
        "Form": "Masters Ribbon",
        "Task": "Export",
        "Date": "",
        "Deadline": "",
        "Status": "Pending",
        "Codeplayers Remarks": "",
        "Client Remarks": ""
    },
    {
        "Module": "Common",
        "Sub module": "Transactions",
        "Form": "Masters Ribbon",
        "Task": "Settings",
        "Date": "",
        "Deadline": "",
        "Status": "Done",
        "Codeplayers Remarks": "",
        "Client Remarks": ""
    },
    {
        "Module": "Common",
        "Sub module": "Transactions",
        "Form": "Masters Ribbon",
        "Task": "Register",
        "Date": "",
        "Deadline": "",
        "Status": "TRP",
        "Codeplayers Remarks": "",
        "Client Remarks": ""
    },
    {
        "Module": "Common",
        "Sub module": "Transactions",
        "Form": "Masters Ribbon",
        "Task": "Duplicate",
        "Date": "",
        "Deadline": "",
        "Status": "Pending",
        "Codeplayers Remarks": "",
        "Client Remarks": ""
    },
    {
        "Module": "Raw Materials",
        "Sub module": "Transactions",
        "Form": "Purchase Order",
        "Task": "Concept",
        "Date": "",
        "Deadline": "",
        "Status": "Done",
        "Codeplayers Remarks": "",
        "Client Remarks": ""
    },
    {
        "Module": "Raw Materials",
        "Sub module": "Transactions",
        "Form": "Purchase Order",
        "Task": "New",
        "Date": "",
        "Deadline": "",
        "Status": "Pending",
        "Codeplayers Remarks": "",
        "Client Remarks": ""
    }
];
export default data;